In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("job_descriptions.csv")
df.head(2)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."

In [3]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [4]:
df.describe()

             Job Id      latitude     longitude  Company Size
count  1.615940e+06  1.615940e+06  1.615940e+06  1.615940e+06
mean   1.548935e+15  1.937743e+01  1.639926e+01  7.370467e+04
std    8.946722e+14  2.355690e+01  7.066762e+01  3.529886e+04
min    1.817948e+11 -4.090060e+01 -1.751982e+02  1.264600e+04
25%    7.740508e+14  5.152100e+00 -1.531010e+01  4.311400e+04
50%    1.547858e+15  1.807080e+01  1.914510e+01  7.363300e+04
75%    2.323729e+15  3.907420e+01  4.757690e+01  1.043000e+05
max    3.099618e+15  7.170690e+01  1.780650e+02  1.348340e+05

In [5]:
df.info

<bound method DataFrame.info of                    Job Id     Experience Qualifications Salary Range  \
0        1089843540111562  5 to 15 Years         M.Tech    $59K-$99K
1         398454096642776  2 to 12 Years            BCA   $56K-$116K
2         481640072963533  0 to 12 Years            PhD   $61K-$104K
3         688192671473044  4 to 11 Years            PhD    $65K-$91K
4         117057806156508  1 to 12 Years            MBA    $64K-$87K
...                   ...            ...            ...          ...
1615935   134563577088850  0 to 12 Years         B.Tech   $64K-$114K
1615936   618604818190827  2 to 14 Years         M.Tech   $62K-$130K
1615937   615471367712200  4 to 15 Years            BCA    $60K-$96K
1615938   804137342023945  5 to 15 Years            BCA   $65K-$103K
1615939   404645755314484  1 to 11 Years            BBA   $56K-$109K

                  location            Country  latitude  longitude  Work Type  \
0                  Douglas        Isle of Man   54.2361    -4.5481     Intern
1                 Ashgabat       Turkmenistan   38.9697    59.5563     Intern
2                    Macao   Macao SAR, China   22.1987   113.5439  Temporary
3               Porto-Novo              Benin    9.3077     2.3158  Full-Time
4                 Santiago              Chile  -35.6751   -71.5429     Intern
...                    ...                ...       ...        ...        ...
1615935  Malabo (de jure),  Equatorial Guinea    1.6508    10.2679  Full-Time
1615936             Warsaw             Poland   51.9194    19.1451     Intern
1615937           Ashgabat       Turkmenistan   38.9697    59.5563  Part-Time
1615938        Ouagadougou       Burkina Faso   12.2383    -1.5616  Full-Time
1615939             Asmara            Eritrea   15.1794    39.7823  Part-Time

         Company Size  ...                Contact  \
0               26801  ...   001-381-930-7517x737
1              100340  ...           461-509-4216
2               84525  ...             9687619505
3              129896  ...  +1-820-643-5431x47576
4               53944  ...      343.975.4702x9340
...               ...  ...                    ...
1615935         18281  ...           950-451-5843
1615936         63621  ...     676.387.1572x71877
1615937        114287  ...      537.384.6193x5284
1615938         45009  ...     (484)257-4755x5346
1615939         87637  ...          (989)703-9723

                            Job Title                        Role  \
0        Digital Marketing Specialist        Social Media Manager
1                       Web Developer      Frontend Web Developer
2                  Operations Manager     Quality Control Manager
3                    Network Engineer   Wireless Network Engineer
4                       Event Manager          Conference Manager
...                               ...                         ...
1615935           Mechanical Engineer  Mechanical Design Engineer
1615936                    IT Manager                 IT Director
1615937           Mechanical Engineer  Mechanical Design Engineer
1615938                HR Coordinator        Training Coordinator
1615939                 Event Planner             Wedding Planner

                  Job Portal  \
0                   Snagajob
1                   Idealist
2               Jobs2Careers
3                   FlexJobs
4               Jobs2Careers
...                      ...
1615935         ZipRecruiter
1615936              USAJOBS
1615937               Indeed
1615938  Stack Overflow Jobs
1615939              USAJOBS

                                           Job Description  \
0        Social Media Managers oversee an organizations...
1        Frontend Web Developers design and implement u...
2        Quality Control Managers establish and enforce...
3        Wireless Network Engineers design, implement, ...
4        A Conference Manager coordinates and manages c...
...                                                    ...
1615935  Mechanical Design Engineers create and develop...
1615936  An IT Director oversees an organizations IT de...
1615937  Mechanical Design Engineers create and develop...
1615938  Training Coordinators design and implement emp...
1615939  Wedding Planners specialize in organizing wedd...

                                                  Benefits  \
0        {'Flexible Spending Accounts (FSAs), Relocatio...
1        {'Health Insurance, Retirement Plans, Paid Tim...
2        {'Legal Assistance, Bonuses and Incentive Prog...
3        {'Transportation Benefits, Professional Develo...
4        {'Flexible Spending Accounts (FSAs), Relocatio...
...                                                    ...
1615935  {'Employee Assistance Programs (EAP), Tuition ...
1615936  {'Health Insurance, Retirement Plans, Paid Tim...
1615937  {'Tuition Reimbursement, Stock Options or Equi...
1615938  {'Casual Dress Code, Social and Recreational A...
1615939  {'Transportation Benefits, Professional Develo...

                                                    skills  \
0        Social media platforms (e.g., Facebook, Twitte...
1        HTML, CSS, JavaScript Frontend frameworks (e.g...
2        Quality control processes and methodologies St...
3        Wireless network design and architecture Wi-Fi...
4        Event planning Conference logistics Budget man...
...                                                    ...
1615935  Mechanical engineering CAD software (e.g., Sol...
1615936  Strategic IT planning Leadership and managemen...
1615937  Mechanical engineering CAD software (e.g., Sol...
1615938  Training program coordination Training materia...
1615939  Wedding planning Venue selection Catering and ...

                                          Responsibilities  \
0        Manage and grow social media accounts, create ...
1        Design and code user interfaces for websites, ...
2        Establish and enforce quality control standard...
3        Design, configure, and optimize wireless netwo...
4        Specialize in conference and convention planni...
...                                                    ...
1615935  Design mechanical systems, components, and pro...
1615936  Provide strategic leadership for IT department...
1615937  Design mechanical systems, components, and pro...
1615938  Coordinate employee training programs, track t...
1615939  Specialize in wedding planning, assisting coup...

                                  Company  \
0                       Icahn Enterprises
1            PNC Financial Services Group
2        United Services Automobile Assn.
3                                    Hess
4                            Cairn Energy
...                                   ...
1615935               The Hershey Company
1615936                               EQT
1615937                               KLA
1615938               Mahindra & Mahindra
1615939                     Ashtead Group

                                           Company Profile
0        {"Sector":"Diversified","Industry":"Diversifie...
1        {"Sector":"Financial Services","Industry":"Com...
2        {"Sector":"Insurance","Industry":"Insurance: P...
3        {"Sector":"Energy","Industry":"Mining, Crude-O...
4        {"Sector":"Energy","Industry":"Energy - Oil & ...
...                                                    ...
1615935  {"Sector":"Food and Beverage/Confectionery","I...
1615936  {"Sector":"Energy","Industry":"Energy","City":...
1615937  {"Sector":"Technology","Industry":"Semiconduct...
1615938  {"Sector":"Automotive","Industry":"Automotive"...
1615939  {"Sector":"Equipment Rental","Industry":"Equip...

[1615940 rows x 23 columns]>

In [6]:
df.shape

(1615940, 23)

In [7]:
df.Qualifications

0          M.Tech
1             BCA
2             PhD
3             PhD
4             MBA
            ...
1615935    B.Tech
1615936    M.Tech
1615937       BCA
1615938       BCA
1615939       BBA
Name: Qualifications, Length: 1615940, dtype: object

In [8]:
df.rename(columns={'Job Id':'Job_Id','Salary Range':'Salary_Range','Work Type':'Work_Type','Company Size':'Company_Size','Job Posting Date':'Job_Posting_Date','Contact Person':'Contact_Person','Job Title':'Job_Title','Job Portal':'Job_Portal','Job Description':'Job_Description','Company Profile':'Company_Profile'},inplace=True)

In [9]:
df.Company_Profile

0          {"Sector":"Diversified","Industry":"Diversifie...
1          {"Sector":"Financial Services","Industry":"Com...
2          {"Sector":"Insurance","Industry":"Insurance: P...
3          {"Sector":"Energy","Industry":"Mining, Crude-O...
4          {"Sector":"Energy","Industry":"Energy - Oil & ...
                                 ...
1615935    {"Sector":"Food and Beverage/Confectionery","I...
1615936    {"Sector":"Energy","Industry":"Energy","City":...
1615937    {"Sector":"Technology","Industry":"Semiconduct...
1615938    {"Sector":"Automotive","Industry":"Automotive"...
1615939    {"Sector":"Equipment Rental","Industry":"Equip...
Name: Company_Profile, Length: 1615940, dtype: object

In [10]:
df.head(3)

,Job_Id,Experience,Qualifications,Salary_Range,location,Country,latitude,longitude,Work_Type,Company_Size,...,Contact,Job_Title,Role,Job_Portal,Job_Description,Benefits,skills,Responsibilities,Company,Company_Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."

In [11]:
df.isnull().sum()

Job_Id                 0
Experience             0
Qualifications         0
Salary_Range           0
location               0
Country                0
latitude               0
longitude              0
Work_Type              0
Company_Size           0
Job_Posting_Date       0
Preference             0
Contact_Person         0
Contact                0
Job_Title              0
Role                   0
Job_Portal             0
Job_Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company_Profile     5478
dtype: int64

In [12]:
df.shape

(1615940, 23)

In [13]:
df.dropna(inplace=True)

In [14]:
df.isnull().sum()

Job_Id              0
Experience          0
Qualifications      0
Salary_Range        0
location            0
Country             0
latitude            0
longitude           0
Work_Type           0
Company_Size        0
Job_Posting_Date    0
Preference          0
Contact_Person      0
Contact             0
Job_Title           0
Role                0
Job_Portal          0
Job_Description     0
Benefits            0
skills              0
Responsibilities    0
Company             0
Company_Profile     0
dtype: int64

In [15]:
df.drop_duplicates(inplace=True)